# Generated by Django 5.1.2 on 2024-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkSharing', '0003_alter_link_options_remove_link_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
