# Generated by Django 5.1.2 on 2024-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkSharing', '0004_alter_link_platform_alter_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
