# Generated by Django 5.1.2 on 2024-10-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkSharing', '0005_alter_link_options_link_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='link',
            name='position',
        ),
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
