# Generated by Django 5.1.2 on 2024-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkSharing', '0006_alter_link_options_remove_link_position_link_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
