# Generated by Django 5.1.2 on 2024-10-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkSharing', '0007_alter_link_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-order']},
        ),
    ]
